# Generated by Django 4.0 on 2021-12-26 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('robots', '0002_alter_id_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rule',
            name='id',
            field=models.AutoField(auto_created=True,
                                   primary_key=True,
                                   serialize=False,
                                   verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='url',
            name='id',
            field=models.AutoField(auto_created=True,
                                   primary_key=True,
                                   serialize=False,
                                   verbose_name='ID'),
        ),
    ]
